In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
df=pd.read_csv('Restaurant_Reviews.tsv', delimiter='\t', quoting=3)
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [16]:
df.shape

(1000, 2)

In [17]:
#cleaning the dataset
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\laksh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [20]:
corpus=[]
for i in range(0,1000):    
    review=re.sub('[^a-zA-Z]',' ', df['Review'][i]) #to take only alphabets
    review=review.lower() #to convert to lower
    review=review.split() #converts to list

    ps=PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))] #removes extra words like the, a, an etc and stemming is done to remove tense
    review=' '.join(review)
    corpus.append(review)

In [21]:
#corpus

In [28]:
#creating a bag of words model using tokenization
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1500)
X=cv.fit_transform(corpus).toarray() #toarray converts to matrix

In [29]:
X.shape

(1000, 1500)

In [32]:
y=df.iloc[:,1].values

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [59]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [62]:
knn_classifier = KNeighborsClassifier(n_neighbors = 3)
knn_classifier.fit(X_train, y_train)
y_pred=knn_classifier.predict(X_test)

In [63]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[75, 22],
       [51, 52]], dtype=int64)

In [65]:
svc_classifier = SVC(kernel = 'linear')
svc_classifier.fit(X_train, y_train)
y_pred=svc_classifier.predict(X_test)

In [66]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[74, 23],
       [33, 70]], dtype=int64)

In [67]:
dt_classifier = DecisionTreeClassifier(max_features = 6, random_state = 0)
dt_classifier.fit(X_train, y_train)
y_pred=dt_classifier.predict(X_test)

In [68]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[66, 31],
       [30, 73]], dtype=int64)

In [71]:
rf_classifier = RandomForestClassifier(n_estimators = 200, random_state = 0)
rf_classifier.fit(X_train, y_train)
y_pred=rf_classifier.predict(X_test)

In [72]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[86, 11],
       [47, 56]], dtype=int64)

In [73]:
from sklearn.naive_bayes import GaussianNB

In [74]:
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred=classifier.predict(X_test)

In [75]:
#making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[55, 42],
       [12, 91]], dtype=int64)